#!/bin/bash
touch ~/.local/share/applications/$2.desktop
echo "[Desktop Entry]" > ~/.local/share/applications/$2.desktop
echo "Version=1.0" >> ~/.local/share/applications/$2.desktop
echo "Name=$2" >> ~/.local/share/applications/$2.desktop
echo "Comment=Generated by Cmd2App" >> ~/.local/share/applications/$2.desktop
echo "Exec=$1" >> ~/.local/share/applications/$2.desktop
echo "Icon=$3" >> ~/.local/share/applications/$2.desktop
echo "Terminal=false" >> ~/.local/share/applications/$2.desktop
echo "Type=Application" >> ~/.local/share/applications/$2.desktop

