echo -e "#include<stdlib.h>" > "$1.c"
echo -e "#include<string.h>" >> "$1.c"
echo -e "" >> "$1.c"
echo -e "int main(){" >> "$1.c"
echo -e "char a[5000000];" >> "$1.c"
echo -e "strcpy(a,\"\");" >> "$1.c"
cat "$1" | sed "s/\\\/\\\\\\\/g" |  sed "s|\"|\\\\\"|g" | sed "s/^/strcat(a,\"/" | sed "s/$/\\;\");/" >> "$1.c"
echo -e "system(a);" >> "$1.c"
echo -e "return 0;" >> "$1.c"
echo -e "}" >> "$1.c"
